spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:leethub_helper}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

github.client-id=${GITHUB_CLIENT_ID}
github.client-secret=${GITHUB_CLIENT_SECRET}
github.redirect-uri=https://leetgit-dashboard-v1-production.up.railway.app/github/callback

jwt.secret=${JWT_SECRET}

logging.level.org.springframework.security=INFO